### ISSUE TITLE
pip install sqlcrush requires postgresql

### ISSUE THREAD

**Issue by lucvanbraekel** [coffeeandscripts/sqlcrush#3]
When installing through pip, installation of psycopg protests that it can't find pg_config executable. After installing postgresql (or more exactly, postgresql-server-dev-9.3), error goes away and "pip install sqlcrush" completes without errors.  So I could solve this problem, but I wonder why I have to install postgresql if I only want to use sqlcrush with sqlite.

**Comment by coffeeandscripts** [comment]
Thanks for raising this issue.
I am honestly not completely sure at the moment as why that specifically occurs but I can hazard a guess. I suspect that psycopg not only requires postgresql as a dependency but relies on a specific file that is created at the installation of postgresql.
As for why you need to install postgresql when you just want to use it with sqlite: I wanted to create an program that could interface with the three main database formats, ie sqlite, MySQL and postgreSQL. Hence in order to have the program run any of them, I needed to install all dependencies. I hope that helps clarify why you have to install it.
I will update the setup.py to force installation of postgresql.
