### ISSUE TITLE
Larg db lag.

### ISSUE THREAD

**Issue by zelds** [coffeeandscripts/sqlcrush#4]
Only i have lag, like a "ping - 900", in really huge database ?

**Comment by coffeeandscripts** [comment]
Thanks for opening this issue. I'm aware of this issue and am working on a fix.

**Comment by zelds** [comment]
I wanna help to you but i`m just junior python/django developer.

**Comment by coffeeandscripts** [comment]
I'm a medical student with 8 months Python experience. I'm sure you can help if you want to learn. I'd be happy to teach you what I've done.

**Comment by coffeeandscripts** [comment]
It's been a while but this has been updated so that the database isn't accessed on every loop. It is only accessed when a change has been made by the user. This will be useful for moderately large databases, but still with millions and millions of records, it will still lag understandably. Working on fixing that too.
